export const GET_LIST_OF_MARATHONS = "GET_LIST_OF_MARATHONS"
export const SAVE_MARATHON = "SAVE_MARATHON"
export const UPDATE_MARATHON = "UPDATE_MARATHON"
export const DELETE_MARATHON = "DELETE_MARATHON"

export const GET_LIST_OF_SPRINTS = "GET_LIST_OF_SPRINTS"
export const SAVE_SPRINT = "SAVE_SPRINT"
export const UPDATE_SPRINT = "UPDATE_SPRINT"
export const DELETE_SPRINT = "DELETE_SPRINT"

export const GET_LIST_OF_TASKS = "GET_LIST_OF_TASKS"
export const SAVE_TASK = "SAVE_TASK"
export const DELETE_TASK = "DELETE_TASK"
export const UPDATE_TASK = "UPDATE_TASK"

export const GET_LIST_OF_USERS = "GET_LIST_OF_USERS"
export const DELETE_USER = "DELETE_USER"

export const GET_PROGRESSES_BY_TASK = "GET_PROGRESSES_BY_TASK"
export const GET_PROGRESSES_BY_USER = "GET_PROGRESSES_BY_USER"
export const DELETE_PROGRESS = "DELETE_PROGRESS"
export const GET_USERS_BY_MARATHON = "GET_USERS_BY_MARATHON"
export const PROGRESS_SOLUTION = "PROGRESS_SOLUTION"
